language: elixir
elixir:
  - '1.3'
otp_release:
  - '18.2.1'

matrix:
  include:
    - elixir: '1.4'
      otp_release: '19.3.6'
    - elixir: '1.5'
      otp_release: '20.3.1'
    - elixir: '1.6'
      otp_release: '20.3.1'
    - elixir: '1.7'
      otp_release: '20.3.1'
    - elixir: '1.8'
      otp_release: '20.3.1'
